# Generated by Django 4.2 on 2025-04-04 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('especialidade', models.CharField(choices=[('CLI', 'CLINICO'), ('CARDIO', 'CARDIOLOGISTA'), ('ONCO', 'ONCOLOGISTA')], max_length=40)),
                ('crm', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=80)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('REA', 'REALIZADO'), ('AGEND', 'AGENDADO'), ('CANCEL', 'CANCELADO')], max_length=100)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
            ],
        ),
    ]
